name: Bug report
description: Report something that is not working
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please include as much detail as you can.
  - type: input
    id: macos_version
    attributes:
      label: macOS version
      placeholder: "e.g. 14.6.1"
    validations:
      required: true
  - type: input
    id: hammerspoon_version
    attributes:
      label: Hammerspoon version
      placeholder: "e.g. 0.9.100"
    validations:
      required: false
  - type: textarea
    id: what_happened
    attributes:
      label: What happened
      description: What did you see? Include any console errors from Hammerspoon.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What you expected
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
